spring:
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:mem:testdb
    username: sa
    password:
    initialization-mode: always

mybatis:
  mapper-locations: mybatis/**/*.xml

logging:
  level:
    jdbc:
      sqlonly: INFO
      sqltiming: OFF
      resultsettable: INFO
      audit: OFF
      resultset: OFF
      connection: OFF
    com:
      atoz_develop:
        mybatissample:
          repository: TRACE